// Command contracts exports or checks every code-owned public artifact.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"

	"github.com/Liapoldus/forms-db/contracts"
)

func run(check bool, root string) error {
	files, err := contracts.Documents()
	if err != nil {
		return err
	}
	output, err := os.OpenRoot(root)
	if err != nil {
		return err
	}
	defer func() {
		if err := output.Close(); err != nil {
			panic("close contract output root")
		}
	}()
	expected := map[string]bool{}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		expected[filepath.FromSlash(name)] = true
		contents := files[name]
		target := filepath.FromSlash(name)
		if check {
			stored, err := output.ReadFile(target)
			if err != nil || !bytes.Equal(stored, contents) {
				return fmt.Errorf("stale contract: %s", name)
			}
			continue
		}
		if err := output.MkdirAll(filepath.Dir(target), 0o750); err != nil {
			return err
		}
		if err := output.WriteFile(target, contents, 0o600); err != nil {
			return err
		}
	}
	return filepath.WalkDir(filepath.Join(root, "v1"), func(name string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		relative, err := filepath.Rel(root, name)
		if err != nil {
			return err
		}
		if !expected[relative] {
			return fmt.Errorf("unowned contract: %s", relative)
		}
		return nil
	})
}

func main() {
	check := flag.Bool("check", false, "compare generated bytes and complete artifact inventory")
	root := flag.String("out", "contracts", "artifact output directory")
	flag.Parse()
	if err := run(*check, *root); err != nil {
		if _, writeErr := fmt.Fprintln(os.Stderr, err); writeErr != nil {
			os.Exit(1)
		}
		os.Exit(1)
	}
}
